### PR TITLE
Add CustomMessage to AgentToServer and ServerToAgent

### PR DESCRIPTION
**Pull request by andykellr**
See https://github.com/open-telemetry/opamp-spec/issues/49

It was easiest for me to start here. If we agree on the direction of this, I plan to do the following: 

* update the opamp-spec
* add OnCustomMessage method to the client Callbacks interfaces
* add SendCustomMessage to the OpAMPClient
* add implementation to the client and server
* add tests for that implementation

### CODE REVIEW

**Comment by andykellr** [comment]
@tigrannajaryan Let me know what you think of this direction.

**Comment by andykellr** [comment]
I realized overnight that we should add a hash so it is clear that the response is appropriately associated with the last message.

I also stubbed the client callback, which I don't think is perfect, so feedback is welcome. Obviously none if this compiles because I added the method and didn't implement it anywhere. I also didn't generate the protobuf code.

**Comment by tigrannajaryan** [comment]
Discussed 3 topics today:
- Describe uses cases to make the motivation clear
- Explain possible communication patterns (request/response only or can stream unidirectionally or bidirectionally?)
- Consider using sequence ids instead of hashes

**Comment by andykellr** [comment]
Closing while spec is being finalized and discussion is happening in the spec repo.

**Pull request closed without merging**
