### PR TITLE
Small fixes to the examples

### PR DESCRIPTION
**Pull request by UVduane**
* supervisor would throw a nil dereference error on startup
 * server html was referencing a nonexistent protobuf attribute

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@UVduane thank you for the PR.

Please sign the CLA so that we can accept contributions.

**Comment by tigrannajaryan** [comment]
This also needs a more detailed description of the problem, steps to reproduce, etc.

**Comment by UVduane** [comment]
@tigrannajaryan Thanks.  I'm working through the CLA process with company right now.  Process-wise, would you like issues entered for the problems I found?  (I know some projects prefer this, and I probaly should have asked first)

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan Thanks. I'm working through the CLA process with company right now. Process-wise, would you like issues entered for the problems I found? (I know some projects prefer this, and I probaly should have asked first)

We prefer that too, although for small issues it is not mandatory.

However, I would definitely prefer that this PR is split into 2 separate PRs, each fixing one of the problems, since they are not related in any way. And, importantly, for bugs we need reproduction steps to confirm the bug.

**Comment by UVduane** [comment]
You got it.  I'll close this and do some housekeeping w/ issues and PRs to split it all up and document everything.  Thank you for getting the noob pointed in the right direction.

**Pull request closed without merging**
