### PR TITLE
Initial client interfaces and types

### PR DESCRIPTION
**Pull request by tigrannajaryan**
This is a possible way to design the client API. I would like
some feedback on this or possibly an alternate API suggestion
for the client.

This one uses callbacks. I considered a channel-based approach
to notify the agent about messages but it async nature of channels
makes it difficult to return responses to the server.

Any other thoughts on a better API for the client?

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@open-telemetry/opamp-go-approvers please have a look and feel free to suggest a different way to structure the API. I just want to start the ball rolling.

**Comment by djaglowski** [comment]
I like the callbacks interface. Aside from doing what we need in an elegant way, it provides an easy point of entry for alternate implementations of the message handling. 

A question this raises for me, is whether we should provide a mechanism for additional user-defined message handling, so that the same websocket can be used for any vendor-specific control messages. Something like:
```go
type Callbacks interface {
	...
	OnGenericMessage(messageType string, messageContent interface{})
```

This doesn't need to be a concern of this proposal - just pointing out a possibility that may be useful.

**Comment by tigrannajaryan** [comment]
> A question this raises for me, is whether we should provide a mechanism for additional user-defined message handling, so that the same websocket can be used for any vendor-specific control messages.

This is a very good question and something I have been thinking about possibly adding to the spec. :-)

**Comment by tigrannajaryan** [comment]
@open-telemetry/opamp-go-approvers please review.

**Review by pmm-sumo — APPROVED** [review]

**Pull request merged**
