### PR TITLE
Make Hash field calculations internal responsibility

### PR DESCRIPTION
**Pull request by tigrannajaryan**
The Hash is now calculated internally by the client instead of requiring
the caller to use the helper function to calculate the Hash before
passing the message to the client.

### CODE REVIEW

**Review by pmm-sumo — APPROVED** [review]

**Comment by andykellr** [comment]
This looks good, but should we keep helpers or provide something similar for the server to use? Particularly with the json encode and the issue mentioned in #70, it may not be obvious how the server should compute a hash to compare with the client hash.

**Comment by andykellr** [comment]
It should be possible to internalize the hash computation on the server side as well, but I haven't had time to think though the changes required.

**Comment by tigrannajaryan** [comment]
> This looks good, but should we keep helpers or provide something similar for the server to use? Particularly with the json encode and the issue mentioned in #70, it may not be obvious how the server should compute a hash to compare with the client hash.

The server should not need to computer the hash. It only needs to store and compare. See example implementation: https://github.com/open-telemetry/opamp-go/blob/dfbe616ffb2211c2e75870f461e4521f1419de94/internal/examples/server/data/agent.go#L113

However if we find that for some other cases it is needed we can refactor again to make them publicly available helpers.

**Comment by tigrannajaryan** [comment]
Rebased and conflicts resolved.

Also need to fix https://github.com/open-telemetry/opamp-go/issues/70 but will do in a separate PR.

**Review by andykellr — APPROVED** [review]

**Comment by andykellr** [comment]
> > This looks good, but should we keep helpers or provide something similar for the server to use? Particularly with the json encode and the issue mentioned in #70, it may not be obvious how the server should compute a hash to compare with the client hash.
> 
> The server should not need to computer the hash. It only needs to store and compare. See example implementation:
> 
> https://github.com/open-telemetry/opamp-go/blob/dfbe616ffb2211c2e75870f461e4521f1419de94/internal/examples/server/data/agent.go#L113
> 
> However if we find that for some other cases it is needed we can refactor again to make them publicly available helpers.

I was thinking of EffectiveConfig, not AgentDescription, but it's a similar concern.

https://github.com/open-telemetry/opamp-go/blob/dfbe616ffb2211c2e75870f461e4521f1419de94/internal/examples/server/data/agent.go#L254

**Comment by tigrannajaryan** [comment]
> I was thinking of EffectiveConfig, not AgentDescription, but it's a similar concern.

Right. I think the server doesn't need to compute the hashes.

**Pull request merged**
