### PR TITLE
Ensure client includes AgentDescription on Reconnect

### PR DESCRIPTION
**Pull request by dsvanlani**
Resolves: https://github.com/open-telemetry/opamp-go/issues/55

This PR ensures that the client includes AgentDescription every time it connects to the server, not just after `client.Start`.

Current behavior:
- Clients connection to server is interrupted.
- Client reconnects.
- Client does not prepare a "first status message" with an `AgentDescription`.

Expected behavior:
- Clients connection to server is interrupted.
- Client reconnects.
- Client prepares and sends a status including AgentDescription.

### CODE REVIEW

**Review by andykellr — APPROVED** [review]
I collaborated with @dsvanlani on this fix so I would appreciate another review.

**Review by tigrannajaryan — APPROVED** [review]
LGTM

**Comment by tigrannajaryan** [comment]
Thanks for the fix.

**Comment by tigrannajaryan** [comment]
I may have been too quick to merge this.

Re-reading the spec, it says:
```
The Agent MUST send a status report:
* First time immediately after connecting to the Server. The status report MUST
  be the first message sent by the Agent.
* Subsequently every time the status of the Agent changes.
```

Nowhere does it says that the AgentDescription must be also included in the status report. On the contrary, [the spec says](https://github.com/open-telemetry/opamp-spec/blob/410dc86792d6109050e767a1d76de12a5b9f0129/specification.md?plain=1#L624):
```
<h4 id="agent_description">agent_description</h4>

The description of the agent, its type, where it runs, etc. See
[AgentDescription](#agentdescription-message) message for details.

This field SHOULD be unset if no Agent description fields have changed since the
last StatusReport was sent.
```

So, this fix it correct that it sends the status report after reconnect (it was a bug that we didn't), but we now unnecessarily include the AgentDescription in these subsequent status reports.

@dsvanlani Can you do a follow-up PR that corrects this behavior?

**Pull request merged**
