### PR TITLE
Changes to set the ServerOfferedVersion and ServerOfferedHash always

### PR DESCRIPTION
**Pull request by phanidevavarapu**
This PR will fix the bug https://github.com/open-telemetry/opamp-go/issues/245, the ServerOfferedVersion and ServerOfferedHash are only set when the package is sent from the server the very first time. 

The changes in this PR will make sure that the info is set all the time.

### CODE REVIEW

**Comment by srikanthccv** [comment]
Please add a test case. Let try to include cases one where the installation of new version fails and another that succeeds.

**Comment by phanidevavarapu** [comment]
> Please add a test case. Let's try to include cases one where the installation of the new version fails and another that succeeds.

@srikanthccv the unit test you suggested will cut across all many functions with in this file itself, it will be huge undertaking compared to the code change that I made.

**Comment by srikanthccv** [comment]
Regardless of the size of the change, we should add tests. That's how we prove the change actually fixes it and having a test ensures the issue will not appear again in future.

**Comment by tigrannajaryan** [comment]
> Regardless of the size of the change, we should add tests. That's how we prove the change actually fixes it and having a test ensures the issue will not appear again in future.

+1.  For all bug fixes we want tests that demonstrate that there is a bug (tests fail before the fix) and that the PR fixes the bug (tests pass after the fix).

I understand this adds more work, but this is important for maintaining the quality of the code and being confident about bug fixes.

**Comment by srikanthccv** [comment]
@phanidevavarapu I had opened a PR to add tests against your fork here https://github.com/phanidevavarapu/opamp-go/pull/1. Did you get a chance to look at it?

**Comment by srikanthccv** [comment]
Can you fix the conflicts and update the packagessyncer.go because I commented out the lines to show tests fail.

**Comment by phanidevavarapu** [comment]
@srikanthccv updated the PR, There is a test failing, but I don't see any failures in local.

**Comment by tigrannajaryan** [comment]
TestOfferUpdatedVersion/ws test got stuck, likely an indication of a real problem.

**Comment by phanidevavarapu** [comment]
@tigrannajaryan I am not sure how to approach this now, tests seems to failing and passing at random. Any help to have everything green is really appreciated.

**Comment by srikanthccv** [comment]
While the individual test case `go test -timeout 30s -run ^TestOfferUpdatedVersion$ github.com/open-telemetry/opamp-go/client` passes successfully, running the entire test suite fails with a timeout failure consistently. We need to check why the collective test execution fails and fix it.

**Comment by phanidevavarapu** [comment]
Can we approve and merge this ticket?

**Comment by srikanthccv** [comment]
We need to fix the failing test first. Were you able to find out why the test times out?

**Comment by srikanthccv** [comment]
The changes look good to me. I tried running the workflow multiple times to see if shows flaky behaviour but it passed all runs. I still suspect the test is flaky since it passes now without any changes to the test case.

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@phanidevavarapu this looks good to me, thank you. Can you please resolve the conflicts so that we can merge?

**Comment by phanidevavarapu** [comment]
@tigrannajaryan the merge conflicts are resolved, please go ahead and merge.

**Pull request merged**
