### PR TITLE
Disable codecoverage job since it shows wrong data

### PR DESCRIPTION
**Pull request by tigrannajaryan**
Need help for someone to figure out how to fix this. I wasn't able to.

### CODE REVIEW

**Comment by srikanthccv** [comment]
Do you know why jobs on main point to your fork of repo on codecov app? Here is the output of latest merge to main run
Screenshot 2024-01-13 at 10 36 33 PM

**Comment by srikanthccv** [comment]
I believe that is the issue. From what I understand Codecov uses the last successfully uploaded commit as the base commit to compare against when running the checks on PR. The coverage reports on merge to main are getting uploaded here https://app.codecov.io/github/tigrannajaryan/opamp-go/commits instead of here https://app.codecov.io/github/open-telemetry/opamp-go/commits.

**Comment by tigrannajaryan** [comment]
I manually re-triggered `main` branch build and it seems to have uploading a new commit: https://app.codecov.io/gh/open-telemetry/opamp-go/commits which is good news.

**Comment by tigrannajaryan** [comment]
Re-triggered PR build: https://github.com/open-telemetry/opamp-go/pull/242

**Comment by tigrannajaryan** [comment]
OK, now in codecov's website the report looks correct: https://app.codecov.io/gh/open-telemetry/opamp-go/pull/242 although the comment in the PR posted 2 days ago is wrong. I don't know if there is a way to tell it update the comment and whether this solved the problem completely.

**Comment by tigrannajaryan** [comment]
No, doesn't work. I created a new PR and the same problem: https://github.com/open-telemetry/opamp-go/pull/243

**Comment by srikanthccv** [comment]
Let's see if we can get some help from codecov team to get this issue sorted out https://github.com/codecov/feedback/issues/123.

**Comment by srikanthccv** [comment]
> codecov/project 72.70% (+0.04%) compared to 62d8b60 

This is from the latest PR https://github.com/open-telemetry/opamp-go/pull/244

@tigrannajaryan I think it's working for new PRs created after [this](https://app.codecov.io/gh/open-telemetry/opamp-go/commit/62d8b6039be3617927ad94df836f4359393e311a) successful upload

**Comment by tigrannajaryan** [comment]
> > codecov/project 72.70% (+0.04%) compared to [62d8b60](https://github.com/open-telemetry/opamp-go/commit/62d8b6039be3617927ad94df836f4359393e311a)
> 
> This is from the latest PR #244
> 
> @tigrannajaryan I think it is using correct base commit for new PRs created after [this](https://app.codecov.io/gh/open-telemetry/opamp-go/commit/62d8b6039be3617927ad94df836f4359393e311a) successful upload

OK, it is possible. Let's keep an eye on new PRs.

**Comment by tigrannajaryan** [comment]
Looks like new PRs work properly.

**Pull request closed without merging**
